const path = require('path');
const axios = require('axios').default;

export default class DataLoader {

    // The indexFile is a JSON file generated by /dataset/Sentence Embedding.ipynb
    // The datasetPath is a folder containing the tweets and avatars.
    constructor (datasetPath) {
        this.base = datasetPath;
        this.index = path.join(datasetPath, 'index.json');
    }

    loadData(callback) {
        axios.get(this.index).then(response => {

            console.log(response.data);
            let tweets = response.data.map( tweetData => {
                return {
                    id: tweetData.id,
                    type: 'tweet',
                    name: tweetData.user_name,
                    handle: tweetData.user_handle,
                    content: tweetData.content,
                    vector: tweetData.vector,
                    sentiment: tweetData.sentiment,
                    avatar: path.join(this.base, 'avatars', tweetData.avatar),
                    x: 0, y: 0,
                    cluster: Math.ceil(Math.random() * 4)
                }
            } )

            // for (let tweet of response.data) {
            //     if (tweet.)
            // }
            callback(tweets.slice(0, 150));
        })
    }

}